server:
  port: 8888

spring:
 cloud:
   config:
     server:
       git:
         uri: https://github.com/JasperJiang/mircoservice-configurations.git
         searchPaths: '{application}'
         username: JasperJiang
         password: '{cipher}2a8569ca6f009b24c75571195fe22c81440b6e20436ca00867fda0ebb639cc28'


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
     leaseRenewalIntervalInSeconds: 5
     preferIpAddress: true
     instanceId: ${random.value}:${spring.application.name}:${server.port}


