server:
  port: 8888

spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: 
#          searchPaths: '{application}'
#          username: 
#          password: ''


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
     leaseRenewalIntervalInSeconds: 5
     preferIpAddress: true
     instanceId: ${random.value}:${spring.application.name}:${server.port}


